import type { MeetingDraft } from "./build";

const participants = [
  { id: "priya", name: "Priya Raman", role: "VP Product", org: "Lumen" },
  { id: "aditya", name: "Aditya Sharma", role: "Engineering Lead", org: "Lumen" },
  { id: "marcus", name: "Marcus Bell", role: "Customer Success Manager", org: "Lumen" },
  { id: "sofia", name: "Sofia Alvarez", role: "Solutions Architect", org: "Lumen" },
  { id: "helen", name: "Helen Carter", role: "VP Operations", org: "Acme" },
  { id: "tom", name: "Tom Reyes", role: "IT Director", org: "Acme" },
  { id: "grace", name: "Grace Liu", role: "Security & Compliance Lead", org: "Acme" },
  { id: "jonas", name: "Jonas Weber", role: "Head of Support Operations", org: "Acme" },
];

export const acme: MeetingDraft = {
  id: "acme-enterprise-product-review",
  title: "Acme Enterprise Product Review",
  daysAgo: 1,
  time: [15, 0],
  durationMin: 62,
  template: "product",
  tags: ["Enterprise", "Customer", "Flagship"],
  participants,
  script: [
    // ── Intro ─────────────────────────────────────────────
    ["priya", "Okay, I think everyone is here. Thanks for making the time, this is our quarterly product review for the Acme rollout. Let me do quick introductions since we have a few new faces."],
    ["priya", "On our side it's me, Aditya from engineering, Marcus who owns your customer success, and Sofia, our solutions architect."],
    ["helen", "Great. Helen Carter, I run operations at Acme and I'm the executive sponsor for this rollout. Tom, Grace and Jonas are with me."],
    ["tom", "Tom Reyes, IT director. I own identity, device management, and basically anything that touches our login."],
    ["grace", "Grace Liu, security and compliance. I'll be the one asking the uncomfortable questions today."],
    ["jonas", "Jonas Weber, head of support operations. My team is your largest group of daily users, about three hundred and forty agents."],
    ["priya", "Perfect, that's exactly the mix we wanted. Agenda: first, where the rollout stands and what your teams are saying. Second, security and identity, which I know is the big one. Third, the roadmap for the next two quarters. Last, pricing and next steps."],
    ["helen", "Sounds good. Before we start, I want to be clear about what success looks like. We told our board all four regions would be live by the end of Q1, and I need to know if that is still realistic.", "helen-goal"],
    ["marcus", "Understood, so let me give you the honest status. Two of four regions are live, North America and the UK. That is two hundred and ten active seats out of the five hundred and twenty you contracted.", "status"],
    ["marcus", "Weekly active usage in those two regions is seventy eight percent, which is above our benchmark of sixty five percent for enterprise accounts at this stage."],
    ["helen", "That's encouraging. What is holding back the other two regions?"],
    ["marcus", "Two things. Germany is waiting on the data residency question, and Australia is waiting on identity, because they are on a different directory than everyone else."],

    // ── Rollout & onboarding ──────────────────────────────
    ["jonas", "Can I jump in on onboarding? Because it is what I hear about every single day from my team."],
    ["jonas", "The first week is rough. Agents get the invite, they log in, and then they are dropped into an empty workspace. No guidance, no sample data, nothing. A third of them never come back after day two.", "onboard-pain"],
    ["marcus", "That matches what we see in the data. Day-two drop-off for Acme is thirty one percent, and our average is nineteen."],
    ["priya", "Jonas, that is really useful and honestly a bit painful to hear. Can you say more about what a good first day would look like for an agent?"],
    ["jonas", "Three things. A checklist that tells them what to do first, templates preloaded for our common ticket types, and a way for team leads to see who hasn't finished setup. I shouldn't have to chase people on Slack.", "onboard-ask"],
    ["sofia", "We actually have a guided setup flow in beta. It has the checklist and role-based templates. It isn't turned on for Acme because it depends on the admin console update."],
    ["aditya", "Right. The new admin console ships in the sprint after next. I can have guided setup enabled for Acme's tenant as a pilot by the twelfth if we stay on track.", "pilot-date"],
    ["jonas", "The twelfth would be perfect. We have a new cohort of sixty agents starting on the fifteenth in the UK."],
    ["helen", "So that becomes the pilot cohort. Jonas, are you comfortable using them as the test group?"],
    ["jonas", "Yes, as long as I get a rollback option. If it goes badly I can't have sixty new hires confused on their first week."],
    ["aditya", "Fair. It sits behind a feature flag, so we can turn it off per tenant in seconds."],
    ["marcus", "I'll put together success metrics for the pilot. My proposal is day-two retention above eighty five percent, and time to first completed ticket under thirty minutes.", "metrics"],
    ["jonas", "I like both. Time to first ticket is what I actually care about."],
    ["helen", "Let's make that official. We pilot with the UK cohort, use those two metrics, and review at the end of the month.", "dec-pilot"],
    ["priya", "Agreed. Marcus, can you own the pilot plan and share it with Jonas by Friday?", "act-pilot"],
    ["marcus", "Yes, I'll have it to him by Friday."],
    ["grace", "Quick question on onboarding. Does guided setup collect anything from the agents? I don't want us walking into new data collection without a review."],
    ["sofia", "Good catch. It only stores completion state for each checklist step, no personal data beyond what is already on the account. I can send you the data flow diagram.", "act-dataflow"],
    ["grace", "Please do. I need it for our privacy review anyway."],
    ["jonas", "One more onboarding thing. Our agents in Sydney say the interface is slow on the first load. Is that a known issue?"],
    ["aditya", "Not known to me. Sydney is served from our Singapore edge right now, so first load could be heavy. Can you send me a couple of HAR files?", "sydney"],
    ["jonas", "I'll ask two of the agents to record them and send them over."],
    ["aditya", "Thanks. If it is edge routing, I can probably fix that within a week."],
    ["jonas", "Also, and this is customer feedback straight from the floor, one agent told me it feels like learning a new tool from scratch every time something changes. They want a what's new panel."],
    ["priya", "That's a great insight. We have release notes, but they live on a separate site nobody visits. Let me take an action to look at in-app announcements.", "act-whatsnew"],
    ["helen", "Are there any training materials you can give us before the pilot? Video walkthroughs would help the UK managers."],
    ["marcus", "Yes, we have a library of eight short videos. I'll add the link to the pilot plan."],
    ["jonas", "Perfect. If managers can watch ten minutes before the cohort arrives, it will make a real difference."],
    ["helen", "Good. Let's move on, I want to make sure we leave enough time for security."],

    // ── Security & identity ───────────────────────────────
    ["priya", "Let's move to security and identity, since I know it's the topic with the highest stakes. Tom, do you want to start?"],
    ["tom", "Sure. Our hard requirement is single sign-on through Okta using SAML, and automatic provisioning through SCIM. Today people log in with email and password, and our auditors flagged that.", "sso-req"],
    ["tom", "We cannot go live in Germany or Australia until SSO is in place. Honestly, we shouldn't have gone live in the UK without it."],
    ["helen", "Tom, that's a fair point, but I made the call to move ahead because of the timeline. I'll own that."],
    ["priya", "Let's talk about where we are. Aditya?"],
    ["aditya", "SAML SSO is built and in internal testing. We support Okta, Azure AD, and generic SAML two point oh. The target for general availability is October twenty first.", "sso-date"],
    ["tom", "And SCIM?"],
    ["aditya", "SCIM is later. User provisioning and deprovisioning is planned for early December. Group sync comes after that, probably January.", "scim-date"],
    ["tom", "December is a problem. Without SCIM my team has to deprovision people manually when they leave, and with two hundred plus users across two regions that is a real risk."],
    ["grace", "It's more than a risk, it's an audit finding. If a terminated employee still has access for a week, that is a finding, full stop.", "risk-deprov"],
    ["aditya", "Understood. What if we build a bulk deprovision API in the meantime? It's a small endpoint, I can build it in a couple of days, and Tom's team can script it against your HR system.", "bulk-api"],
    ["tom", "That could work as a stopgap. Can it also kill active sessions immediately, not just disable the account?"],
    ["aditya", "Yes, it revokes all active sessions. I'll confirm that when I write the spec."],
    ["tom", "Then that works for me until SCIM lands."],
    ["helen", "Okay. So the decision is SSO in October, and a stopgap deprovision API until SCIM in December. Does anyone object?", "dec-sso"],
    ["grace", "No objection, but I want it in writing that the stopgap is temporary."],
    ["priya", "Noted. Aditya, can you own the deprovision API spec by next Wednesday?", "act-spec"],
    ["aditya", "Yes, spec by Wednesday, and I'll aim to have it in staging the week after."],
    ["tom", "Can we get a sandbox tenant to test the SSO integration before it goes to production? I don't want to test against real users."],
    ["aditya", "Definitely. I'll provision a sandbox tenant as soon as SAML hits staging, so around the end of next week."],
    ["grace", "Next topic, security review. Our vendor risk process requires your SOC 2 Type II report and a penetration test summary. Do we have those?"],
    ["sofia", "SOC 2 Type II, yes, it was renewed in August. I can send the report under NDA. The pen test summary from the June test is also available.", "act-soc2"],
    ["grace", "Great. Please send both to me directly rather than through the shared folder."],
    ["sofia", "Will do, I'll send both today."],
    ["grace", "Second question, audit logs. What events do you capture, and can I export them to our SIEM?"],
    ["aditya", "We capture logins, permission changes, data exports, and admin actions. Export is currently a CSV download, there's no streaming integration yet."],
    ["grace", "A CSV download won't pass our review. We use Splunk, so we need a streaming feed, or at least an API we can poll.", "audit-req"],
    ["aditya", "An audit log API is on the roadmap for Q1. I can look at whether a polling endpoint can be pulled forward, but I don't want to promise it today.", "audit-q"],
    ["grace", "That's honest, thank you. I would rather have a real date than an optimistic one."],
    ["priya", "Let's leave it as an open question and we'll come back with a committed answer next week.", "q-audit"],
    ["grace", "Third, data residency. Our German entity needs data stored in the EU. Where do you host today?"],
    ["sofia", "Today the primary region is US East. We have an EU region in Frankfurt that's live for two other customers. Moving Acme's German tenant there is possible, but it means a separate workspace, so no shared reporting with the rest of Acme.", "residency"],
    ["helen", "That would be a problem. Our leadership wants one consolidated view across regions."],
    ["sofia", "I understand. Cross-region reporting is on the roadmap but it isn't scheduled, and that's one of the risks we should be upfront about.", "risk-residency"],
    ["grace", "Legally we can consolidate aggregated metrics, just not raw ticket data. So maybe aggregated reporting is enough?"],
    ["sofia", "That could work. Let me sketch an architecture where the EU tenant pushes aggregate metrics to the global dashboard. I'll bring it to the next call.", "act-arch"],
    ["helen", "Please do. That is a big unlock for Germany."],
    ["grace", "Also, I need to know who at Lumen can access our data. Is there a support access policy?"],
    ["marcus", "Yes. Support staff can only access a tenant with explicit customer approval, time limited, and every access is logged. I'll send you the policy document.", "act-policy"],
    ["grace", "Thanks. That's exactly what our reviewers ask about."],
    ["grace", "Last one on this topic. Encryption. At rest and in transit, and who holds the keys?"],
    ["sofia", "AES two fifty six at rest, TLS one point three in transit. Keys are managed in our cloud KMS. Customer-managed keys are available on the enterprise plan but it's an extra setup step."],
    ["grace", "Customer-managed keys would be a nice to have for Germany. Let's not block on it."],
    ["tom", "Agreed. Let's not stack too many requirements on the German go-live."],
    ["grace", "Do you support IP allow-listing for admin access?"],
    ["aditya", "Yes, per-tenant allow lists are available today under admin settings."],
    ["tom", "Good. We will restrict admin access to our corporate VPN ranges."],
    ["grace", "And session timeout. Can we set it to fifteen minutes of inactivity?"],
    ["aditya", "It is configurable between five minutes and twenty four hours, so fifteen is fine."],

    // ── Roadmap ───────────────────────────────────────────
    ["priya", "Let me switch to the roadmap. I'll go through what is committed for the next two quarters."],
    ["priya", "Q4 commitments are SAML SSO, the new admin console, guided setup, and improvements to the reporting dashboard. Q1 is SCIM group sync, the audit log API, and custom roles.", "roadmap"],
    ["jonas", "Custom roles is big for me. Right now everybody is either an admin or an agent. I need team leads to see their team's dashboards without being able to change billing.", "roles-ask"],
    ["priya", "That's exactly the use case. Custom roles are planned for Q1, but I'm hearing they're a higher priority than we thought."],
    ["aditya", "We could split it. A simple team lead role could ship earlier, and fully customizable permissions later. That's about three weeks of work.", "teamlead-split"],
    ["priya", "I like that. Jonas, would a fixed team lead role solve eighty percent of your problem?"],
    ["jonas", "Ninety percent, honestly."],
    ["helen", "Then let's prioritize it. I'd rather have the simple version in November than the perfect version in March.", "dec-teamlead"],
    ["priya", "Decision made, we do the team lead role first. Aditya, can you re-plan and tell me what slips?", "act-replan"],
    ["aditya", "I'll do the re-planning and get back to you by Monday. My guess is the reporting improvements move a bit."],
    ["helen", "Reporting improvements are less important than roles. That's fine with me."],
    ["tom", "Question about the API. We want to connect Lumen to our ticketing data warehouse. What are the rate limits?"],
    ["aditya", "The default is a hundred requests per minute per tenant. For enterprise we can raise it to a thousand, but a sustained bulk sync is better done with our export endpoint."],
    ["tom", "A thousand a minute is plenty. Can we get that set up?"],
    ["sofia", "I'll file the request and confirm today.", "act-ratelimit"],
    ["tom", "One more thing, mobile. Our field team uses tablets. Does the web app work on tablets?"],
    ["sofia", "It's responsive and works on iPad. A native mobile app is not on the roadmap for this year."],
    ["tom", "Web is fine for us."],
    ["helen", "What about the AI features? My board keeps asking about them."],
    ["priya", "We have AI-generated ticket summaries in private beta. I'd suggest Acme joins after SSO is done, so security can review it first.", "ai-beta"],
    ["grace", "I definitely want to review how the AI processes data. Which model providers do you use, and is our data used for training?", "q-ai"],
    ["priya", "We use two providers under zero retention agreements, and customer data is never used for training. Sofia will include that in the security packet."],
    ["grace", "Good. Please make that explicit in the contract too."],
    ["jonas", "For the roadmap, can I ask about search? My agents complain they can't find old tickets by customer name. It's the second most common complaint after onboarding."],
    ["aditya", "Search improvements are in the reporting bucket that will probably slip. But a customer name index is a small change, I can look at that separately."],
    ["jonas", "Even a small fix would help. I'll take it."],
    ["priya", "Let's log it as a small item and not a roadmap commitment. Aditya, please add it to the backlog.", "act-search"],
    ["jonas", "What about the reporting dashboard, what specifically is improving?"],
    ["priya", "Custom date ranges, export to CSV, and scheduled email reports for team leads."],
    ["jonas", "Scheduled email reports would save my leads an hour every Monday."],
    ["helen", "That one I would keep. Can it stay in Q4 even if the rest slips?"],
    ["aditya", "Scheduled reports is the smallest piece. I will try to keep it in scope in the re-plan."],

    // ── Commercials ───────────────────────────────────────
    ["helen", "Let's talk commercials. We contracted five hundred and twenty seats. If we roll out to all four regions, do we stay at that number?"],
    ["marcus", "Your current usage suggests you'll need closer to six hundred. Germany alone is about ninety people and Australia around seventy.", "seats"],
    ["helen", "That's more than we budgeted. Can we get volume pricing above five twenty?"],
    ["marcus", "We can discuss it. Typically it's a ten percent discount on the incremental seats for an annual commitment. I'll need to check with finance for anything more.", "pricing"],
    ["helen", "I'd want fifteen. And I'd want SSO and the audit features included, not sold as an add-on."],
    ["priya", "SSO is included in the enterprise tier already, and the audit log API will be too. On the discount, Marcus will take it to finance."],
    ["marcus", "I'll bring a proposal back by the end of next week.", "act-pricing"],
    ["marcus", "Worth flagging, the contract renews in March, so any new seat pricing would co-term with that date."],
    ["helen", "That works, co-terming keeps procurement simple."],
    ["helen", "That works. And I want to be transparent: if the SSO date slips past October, I'll need to revisit the timeline with my board.", "risk-sso"],
    ["priya", "Understood, and we'll flag any slip immediately, not at the next review."],
    ["tom", "Can we also get a shared channel with your engineering team for the SSO rollout? Email is too slow."],
    ["aditya", "Absolutely. I'll set up a shared Slack channel today.", "act-slack"],
    ["jonas", "Could I get access to it as well, for onboarding issues?"],
    ["aditya", "Sure, I'll add you."],
    ["helen", "One more thing on the timeline. If Germany can't go live until residency is solved, what's the earliest realistic date?"],
    ["sofia", "If we agree the aggregated reporting approach next week, I'd say the EU tenant could be provisioned within three weeks. So late November for Germany, assuming SSO is done.", "germany-date"],
    ["helen", "Late November is acceptable. Australia?"],
    ["marcus", "Australia only depends on SSO and the Sydney performance issue, so mid-November is realistic if both land."],
    ["helen", "Then Q1 is still achievable, though with less buffer than I'd like.", "helen-buffer"],

    // ── Wrap up ───────────────────────────────────────────
    ["tom", "Before we wrap, can I get one thing in writing? A single page listing every identity feature and its date, so I can share it with my auditors."],
    ["priya", "Yes, Sofia will fold that into the security packet."],
    ["helen", "I'd also like Tom to write down the Okta requirements so there is no ambiguity on either side. Tom, can you do that?"],
    ["tom", "Sure, I'll send our Okta requirements to Aditya by Tuesday.", "act-okta"],
    ["priya", "Let me recap the decisions. One, the UK cohort pilots guided setup starting on the twelfth, with two success metrics. Two, SAML SSO in October and a temporary deprovision API until SCIM in December. Three, team lead role first, full custom roles later.", "recap"],
    ["priya", "Actions: Marcus, pilot plan by Friday and pricing proposal next week. Aditya, deprovision API spec Wednesday, re-plan by Monday, the Sydney investigation, and the Slack channel. Sofia, the security packet, data flow diagram, EU architecture sketch, and the rate limit request."],
    ["helen", "That's a clear list. Thank you all, this was the most productive review we've had."],
    ["grace", "Agreed. I'm more comfortable than when I joined the call, and I'll say so in my report."],
    ["marcus", "Thanks everyone. I'll send the written summary and action list this afternoon."],
    ["priya", "Thanks all. Talk next week."],
  ],
  analysis: {
    summary:
      "Quarterly product review of the Acme rollout with Lumen. Two of four regions (North America, UK) are live with 210 of 520 contracted seats and 78% weekly active usage, but a 31% day-two drop-off points to weak onboarding. The team agreed to pilot guided setup with a 60-agent UK cohort from the 12th, to ship SAML SSO by October 21 with a temporary bulk-deprovision API until SCIM arrives in December, and to build a simple team-lead role ahead of full custom roles. Open risks are data residency for Germany, the SIEM-ready audit log API, and Acme's board timeline if SSO slips. Acme expects to need about 600 seats and will receive a discount proposal next week.",
    topics: ["Onboarding", "SAML SSO & SCIM", "Audit logs", "Data residency", "Roadmap", "Pricing", "Team lead role"],
    keyPoints: [
      ["Two of four regions are live: 210 of 520 seats, 78% weekly active usage against a 65% benchmark.", "status"],
      ["Onboarding is the top pain: a third of agents never return after day two because they land in an empty workspace.", "onboard-pain"],
      ["SAML SSO targets general availability on October 21; SCIM provisioning follows in early December.", "sso-date"],
      ["A bulk deprovision API will bridge the gap until SCIM lands, revoking sessions immediately.", "bulk-api"],
      ["Audit logs are CSV-only today; Acme's Splunk SIEM needs a streaming feed or pollable API.", "audit-req"],
      ["EU data residency requires a separate Frankfurt workspace, which breaks consolidated reporting.", "residency"],
      ["Acme needs roughly 600 seats, above the 520 contracted.", "seats"],
      ["Germany could go live in late November if the aggregated-reporting approach is agreed.", "germany-date"],
    ],
    decisions: [
      ["Pilot guided setup with the 60-agent UK cohort starting on the 12th, success measured by day-two retention above 85% and time to first ticket under 30 minutes; review at end of month.", "dec-pilot", "helen"],
      ["Ship SAML SSO in October and use a temporary bulk deprovision API until SCIM arrives in December.", "dec-sso", "helen"],
      ["Build a fixed team-lead role first and defer fully customisable roles.", "dec-teamlead", "helen"],
    ],
    actions: [
      ["Write and share the guided-setup pilot plan with Jonas", "marcus", "act-pilot", "Friday"],
      ["Send the guided-setup data flow diagram to Grace", "sofia", "act-dataflow"],
      ["Investigate slow first load in Sydney using HAR files from Acme agents", "aditya", "sydney", "Next week"],
      ["Write the bulk deprovision API spec (with session revocation)", "aditya", "act-spec", "Next Wednesday"],
      ["Send SOC 2 Type II report and June pen test summary directly to Grace", "sofia", "act-soc2", "Today"],
      ["Send the support access policy document to Grace", "marcus", "act-policy"],
      ["Sketch the EU tenant architecture pushing aggregate metrics to the global dashboard", "sofia", "act-arch", "Next call"],
      ["Re-plan the roadmap around the team-lead role and report what slips", "aditya", "act-replan", "Monday"],
      ["File the API rate-limit increase to 1,000 requests per minute", "sofia", "act-ratelimit", "Today"],
      ["Add customer-name ticket search to the backlog", "aditya", "act-search"],
      ["Look at in-app what's-new announcements", "priya", "act-whatsnew"],
      ["Bring a volume-discount proposal back from finance", "marcus", "act-pricing", "End of next week"],
      ["Set up a shared Slack channel for the SSO rollout and add Jonas", "aditya", "act-slack", "Today"],
      ["Send Acme's Okta requirements to Aditya", "tom", "act-okta", "Tuesday"],
    ],
    highlights: [
      ["Onboarding drop-off", "A third of agents never return after day two. Empty workspace on first login.", "onboard-pain"],
      ["SSO is a hard blocker", "Germany and Australia cannot go live without SSO; auditors already flagged password login.", "sso-req"],
      ["Deprovisioning is an audit finding", "Any terminated employee with lingering access is an automatic finding.", "risk-deprov"],
      ["Board timeline at risk", "If SSO slips past October, Helen must revisit the four-region timeline with her board.", "risk-sso"],
      ["Decision: team-lead role first", "Simple version in November beats the perfect version in March.", "dec-teamlead"],
    ],
    questions: [
      ["Can a polling audit-log endpoint be pulled forward from Q1 for Splunk?", "grace", "q-audit", false],
      ["Which model providers power the AI features and is customer data used for training?", "grace", "q-ai", true],
      ["Can the deprovision API also revoke active sessions?", "tom", "bulk-api", true],
    ],
    risks: [
      ["Terminated employees keep access until SCIM ships in December, an audit finding.", "high", "risk-deprov"],
      ["EU data residency splits Acme's consolidated reporting.", "high", "risk-residency"],
      ["SSO slipping past October forces Acme to renegotiate the timeline with their board.", "high", "risk-sso"],
      ["Audit log API is not scheduled ahead of Q1, blocking Acme's SIEM review.", "medium", "audit-q"],
      ["Less schedule buffer than Acme would like for the Q1 four-region goal.", "medium", "helen-buffer"],
    ],
    sections: {
      problems: [
        ["Agents land in an empty workspace with no guidance; a third never return after day two.", "onboard-pain"],
        ["Team leads cannot view their team's dashboards without admin rights.", "roles-ask"],
        ["Agents cannot find old tickets by customer name.", "roles-ask"],
      ],
      requests: [
        ["Onboarding checklist, preloaded ticket templates and a setup progress view for team leads (Jonas).", "onboard-ask"],
        ["Okta SAML SSO with SCIM provisioning (Tom).", "sso-req"],
        ["Streaming or pollable audit log API for Splunk (Grace).", "audit-req"],
        ["Aggregated cross-region reporting for the EU tenant (Helen).", "residency"],
      ],
      tradeoffs: [
        ["Team-lead role prioritised over full custom roles; reporting improvements slip.", "dec-teamlead"],
        ["SCIM deferred to December; a bulk deprovision API bridges the gap.", "dec-sso"],
        ["AI beta held until after SSO so security can review it first.", "ai-beta"],
      ],
    },
  },
};
