import type { MeetingDraft } from "./build";

const lumen = {
  priya: { id: "priya", name: "Priya Raman", role: "VP Product", org: "Lumen" },
  aditya: { id: "aditya", name: "Aditya Sharma", role: "Engineering Lead", org: "Lumen" },
  marcus: { id: "marcus", name: "Marcus Bell", role: "Customer Success Manager", org: "Lumen" },
  sofia: { id: "sofia", name: "Sofia Alvarez", role: "Solutions Architect", org: "Lumen" },
  dana: { id: "dana", name: "Dana Whitfield", role: "Account Executive", org: "Lumen" },
};

export const roadmap: MeetingDraft = {
  id: "q4-roadmap-planning",
  title: "Q4 Roadmap Planning",
  daysAgo: 5,
  time: [11, 0],
  durationMin: 46,
  template: "product",
  tags: ["Product", "Planning"],
  participants: [lumen.priya, lumen.aditya, lumen.marcus, lumen.sofia, lumen.dana],
  script: [
    ["priya", "Let's lock the Q4 roadmap today. I have a long list and capacity for about half of it, so we need to pick and say why."],
    ["marcus", "Before we start, here's the customer data. Across the twelve enterprise accounts, the top three asks are SSO, better onboarding, and audit log exports. Nothing else is close.", "top-asks"],
    ["dana", "That matches what I hear in deals. In the last month SSO came up in seven out of ten late-stage conversations. Two deals are stalled on it right now.", "sso-deals"],
    ["aditya", "Engineering view: SSO is about six weeks of work with two engineers, and it's mostly done. SCIM adds another three weeks. Onboarding is smaller, maybe four weeks including the admin console dependency."],
    ["priya", "So SSO and onboarding are both in. What about audit logs?"],
    ["sofia", "The CSV export exists but security teams want a streaming API. That's a bigger piece, about five weeks, and it needs the new event pipeline."],
    ["priya", "That sounds like Q1 unless something else falls out."],
    ["aditya", "I'd rather hold it for Q1. If we try to squeeze it in, SSO quality suffers.", "audit-q1"],
    ["priya", "Agreed. Audit log API moves to Q1 and I'll tell Grace's team at Acme it isn't committed for Q4."],
    ["marcus", "One more theme: team leads. Three customers asked for a role where managers can view dashboards but not billing. It's showing up in every onboarding call.", "team-lead-ask"],
    ["aditya", "A minimal role is about three weeks. Full custom roles would be a quarter by itself."],
    ["priya", "Then the minimal role goes in Q4 and full custom roles in Q1. That gives customers something without blocking on the perfect design.", "roles-decision"],
    ["dana", "What about the AI summaries? Prospects ask about it a lot, and it's a strong story in demos."],
    ["priya", "I want to be careful. The beta has good feedback but security teams want to review the data flow, and that will slow enterprise adoption. I'd keep it in private beta this quarter.", "ai-beta"],
    ["dana", "Understood, but can I at least demo it? Even a scripted demo to design partners."],
    ["priya", "Yes, to design partners under NDA. Not on the public pricing page yet."],
    ["sofia", "There's a request from three accounts for a Salesforce integration. It came up during discovery calls."],
    ["priya", "I hear it but it doesn't fit this quarter. Each integration is a real maintenance cost. Let's gather more evidence before committing.", "salesforce-deferred"],
    ["marcus", "For what it's worth, two of those three accounts said they'd use Zapier if we had a webhooks story. Our webhooks are stable now."],
    ["priya", "That's a much cheaper answer. Marcus, can you go back to those accounts and ask if webhooks plus Zapier is enough?", "act-zapier"],
    ["marcus", "Yes, I'll check with them this week."],
    ["aditya", "Capacity check. SSO, guided setup, and the team lead role, plus the admin console, fits Q4 with a little buffer. Adding anything else eats the buffer.", "capacity"],
    ["priya", "Then that's the line. In: SAML SSO, admin console, guided setup, team lead role, and a scheduled-reports improvement. Out: Salesforce, audit log API, custom roles."],
    ["dana", "Can I tell prospects the audit log API is coming in Q1?"],
    ["priya", "Say planned for Q1 and not committed. I don't want a promise we can't keep.", "messaging"],
    ["sofia", "I'll update the roadmap slide with those exact words."],
    ["priya", "Great. Aditya, please turn this into a delivery plan with milestones, and Dana, share the messaging with the sales team.", "act-plan"],
  ],
  analysis: {
    summary:
      "Roadmap planning session that fixed the Q4 scope. Customer data shows SSO, onboarding, and audit log exports as the three dominant asks, with SSO stalling two late-stage deals. Q4 will ship SAML SSO, the admin console, guided setup, a minimal team-lead role and a scheduled-reports improvement. The audit log API, custom roles and a Salesforce integration are deferred, and AI summaries stay in private beta for security review. Sales will describe the audit log API as planned for Q1 but not committed.",
    topics: ["SSO", "Onboarding", "Audit logs", "Team lead role", "AI summaries", "Integrations"],
    keyPoints: [
      ["SSO, onboarding and audit log exports are the top three customer asks across twelve enterprise accounts.", "top-asks"],
      ["SSO came up in seven of ten late-stage deals, and two deals are stalled on it.", "sso-deals"],
      ["Q4 capacity covers SSO, admin console, guided setup and the team lead role with a small buffer.", "capacity"],
      ["Audit log API needs the new event pipeline and moves to Q1.", "audit-q1"],
    ],
    decisions: [
      ["Ship a minimal team-lead role in Q4 and defer full custom roles to Q1.", "roles-decision", "priya"],
      ["Keep AI summaries in private beta this quarter; demo to design partners under NDA only.", "ai-beta", "priya"],
      ["Defer the Salesforce integration until there is more evidence.", "salesforce-deferred", "priya"],
      ["Describe the audit log API as planned for Q1, not committed.", "messaging", "priya"],
    ],
    actions: [
      ["Ask the Salesforce-requesting accounts whether webhooks plus Zapier is enough", "marcus", "act-zapier", "This week"],
      ["Turn the Q4 scope into a delivery plan with milestones", "aditya", "act-plan"],
      ["Share the audit log messaging with the sales team", "dana", "act-plan"],
      ["Update the roadmap slide with the agreed wording", "sofia", "messaging"],
    ],
    highlights: [
      ["SSO is stalling deals", "Two late-stage deals are stalled and SSO appeared in seven of ten conversations.", "sso-deals"],
      ["The Q4 line is drawn", "Any addition consumes the buffer; audit log API, custom roles, Salesforce are out.", "capacity"],
    ],
    questions: [
      ["Can I tell prospects the audit log API is coming in Q1?", "dana", "messaging", true],
      ["Would webhooks plus Zapier be enough instead of a Salesforce integration?", "priya", "act-zapier", false],
    ],
    risks: [
      ["Adding scope would erode the Q4 buffer and hurt SSO quality.", "medium", "capacity"],
      ["Security review of AI data flows may slow enterprise adoption.", "low", "ai-beta"],
    ],
    sections: {
      problems: [
        ["Enterprise buyers are blocked without SSO.", "sso-deals"],
        ["Managers need dashboard access without billing access.", "team-lead-ask"],
      ],
      requests: [
        ["SSO, better onboarding and audit log exports (twelve enterprise accounts).", "top-asks"],
        ["Salesforce integration from three accounts.", "salesforce-deferred"],
      ],
      tradeoffs: [
        ["Minimal team-lead role now, full custom roles later.", "roles-decision"],
        ["Audit log API held for Q1 to protect SSO quality.", "audit-q1"],
        ["Integrations deferred because each carries ongoing maintenance cost.", "salesforce-deferred"],
      ],
    },
  },
};

export const interview: MeetingDraft = {
  id: "interview-senior-frontend-riya-kapoor",
  title: "Interview: Senior Frontend Engineer (Riya Kapoor)",
  daysAgo: 6,
  time: [13, 0],
  durationMin: 42,
  template: "interview",
  tags: ["Hiring", "Interview"],
  participants: [
    { id: "leo", name: "Leo Tan", role: "Frontend Engineer", org: "Lumen" },
    lumen.aditya,
    { id: "riya", name: "Riya Kapoor", role: "Candidate", org: "External" },
  ],
  script: [
    ["leo", "Hi Riya, thanks for joining. I'm Leo, I work on our frontend, and Aditya leads engineering. We'll do about forty minutes: your background, a technical discussion, then your questions."],
    ["riya", "Thanks for having me. I'm excited about this role."],
    ["leo", "Tell us about your most recent project."],
    ["riya", "For the last three years I've been at a fintech startup where I led the rebuild of the customer dashboard. We migrated a jQuery app to React with TypeScript, incrementally, over about nine months.", "background"],
    ["aditya", "How did you migrate incrementally? Big rewrites tend to stall."],
    ["riya", "We mounted React islands inside the old pages and moved one route at a time, starting with the pages with the highest traffic. We tracked the share of traffic served by the new stack, and it reached ninety percent by month seven.", "migration"],
    ["leo", "What went wrong?"],
    ["riya", "Two things. We underestimated shared state between old and new code, and we had a couple of bugs from duplicated auth logic. I'd now extract the auth layer first before migrating anything else.", "reflection"],
    ["leo", "Let's get technical. Say a table renders ten thousand rows and it's slow. What do you do?"],
    ["riya", "First I profile to confirm where the time goes. If it's rendering, I virtualise the list so only visible rows mount. If it's the data, I paginate or aggregate server side. I'd also memoise row components and avoid inline objects as props.", "perf-answer"],
    ["leo", "And with virtualisation, what are the downsides?"],
    ["riya", "Accessibility and find in page. Screen readers need proper row counts and roles, and browser search won't find offscreen rows, so I'd offer an in-app search.", "a11y"],
    ["aditya", "Nice. How do you decide between local state, context, and something like a server cache library?"],
    ["riya", "I treat server data as a cache and keep it in a query library so I don't hand-roll loading and invalidation. UI-only state stays local, and context is for rarely changing values like theme or the current user.", "state"],
    ["aditya", "Have you dealt with real-time data?"],
    ["riya", "Not deeply. I've used websockets for notifications, but I haven't built a collaborative editor or handled conflict resolution.", "gap-realtime"],
    ["leo", "That's honest. We do have some live features, so it's something you'd learn here."],
    ["riya", "I'd be happy to. I learn fastest by pairing on a real problem."],
    ["aditya", "Tell me about a disagreement with a teammate."],
    ["riya", "Our designer wanted an animation-heavy transition that hurt performance on low-end phones. I built a quick prototype and measured frame rate on a cheap device, and we agreed on a simpler version. Data ended the debate.", "conflict"],
    ["leo", "How do you approach testing?"],
    ["riya", "Unit tests for logic, component tests with a testing library for behavior, and a small set of end-to-end tests for the critical flows like login and checkout. I avoid snapshot tests, they mostly create noise.", "testing"],
    ["aditya", "Any experience mentoring?"],
    ["riya", "I mentored two juniors. I did weekly code reviews and pair sessions. One of them was promoted last year, which I'm proud of."],
    ["leo", "Do you have questions for us?"],
    ["riya", "Yes. How does the team handle on-call, and how much of the roadmap is customer-driven versus internal?"],
    ["aditya", "Frontend is not on the primary on-call rotation, and the roadmap is very customer-driven, especially enterprise asks like SSO."],
    ["riya", "That's what I was hoping to hear. Thanks for the time."],
    ["aditya", "Thanks Riya. Recruiting will follow up within three days.", "close"],
  ],
  analysis: {
    summary:
      "Interview with Riya Kapoor for a Senior Frontend Engineer role. She led an incremental jQuery-to-React migration at a fintech, reaching 90% traffic on the new stack in seven months, and reflected candidly on the shared-state and auth pitfalls. Technical answers on list performance, accessibility and state management were strong and specific. The main gap is real-time and collaborative features. She showed good data-driven conflict resolution and mentoring experience. Recruiting will follow up within three days.",
    topics: ["Migration", "Performance", "State management", "Testing", "Mentoring"],
    keyPoints: [
      ["Led a nine-month incremental jQuery to React and TypeScript migration at a fintech.", "background"],
      ["Tracked share of traffic on the new stack and reached 90% by month seven.", "migration"],
      ["Named accessibility and find-in-page as the tradeoffs of list virtualisation.", "a11y"],
      ["Limited experience with real-time collaboration and conflict resolution.", "gap-realtime"],
    ],
    decisions: [
      ["Recruiting will follow up within three days.", "close", "aditya"],
    ],
    actions: [
      ["Send interview feedback to recruiting and follow up with the candidate", "aditya", "close", "Within 3 days"],
    ],
    highlights: [
      ["Strong migration story", "Incremental route-by-route migration tracked by traffic share.", "migration"],
      ["Self-aware about mistakes", "Would extract the auth layer first after duplicating auth logic.", "reflection"],
      ["Gap: real-time features", "Only used websockets for notifications, no collaborative editing.", "gap-realtime"],
    ],
    questions: [
      ["How does the team handle on-call and how customer-driven is the roadmap?", "riya", "close", true],
    ],
    risks: [
      ["Limited real-time experience for a role with live features.", "low", "gap-realtime"],
    ],
    sections: {
      strengths: [
        ["Systematic performance approach: profile, virtualise, then paginate.", "perf-answer"],
        ["Data-driven conflict resolution using a device frame-rate prototype.", "conflict"],
        ["Pragmatic testing strategy with critical-flow end-to-end tests.", "testing"],
      ],
      concerns: [
        ["No experience with collaborative editing or conflict resolution.", "gap-realtime"],
      ],
      evidence: [
        ["Server data as a cache; local state for UI; context only for rarely changing values.", "state"],
        ["Migration reached 90% traffic in seven months by mounting React islands.", "migration"],
      ],
    },
  },
};

export const helix: MeetingDraft = {
  id: "helix-health-onboarding-retro",
  title: "Helix Health Onboarding Retro",
  daysAgo: 8,
  time: [10, 0],
  durationMin: 31,
  template: "general",
  tags: ["Customer", "Onboarding"],
  participants: [
    lumen.marcus,
    lumen.sofia,
    { id: "amara", name: "Amara Nwosu", role: "Clinical Operations Lead", org: "Helix Health" },
  ],
  script: [
    ["marcus", "Thanks for joining, Amara. This is a retro on your first ninety days. What worked, what didn't, and what we should do differently for your next clinic."],
    ["amara", "Overall positive. We're in four clinics now and the staff like the queue view. But I'll be direct, the first two weeks were harder than they should have been.", "overall"],
    ["marcus", "Tell me about the two weeks."],
    ["amara", "The invitation emails went to spam for half of my staff, and the ones who did get in landed on a blank screen. Nobody knew where to start.", "onboarding-pain"],
    ["sofia", "That's the empty workspace problem. We have a guided setup in beta that fixes it. It's rolling out to a pilot customer soon."],
    ["amara", "I'd love to be next after the pilot. My next clinic opens in November."],
    ["marcus", "Let's plan on it. What else?"],
    ["amara", "Permissions. My clinic managers can't see their own reports without being admins, and I don't want them touching billing.", "roles"],
    ["marcus", "That's a widely requested feature. A team lead role is planned for Q4."],
    ["amara", "Good. Also, HIPAA. My compliance officer wants a signed business associate agreement, and she hasn't seen it yet.", "baa"],
    ["marcus", "That should have been in your contract pack. I'll chase legal today.", "act-baa"],
    ["sofia", "I'll also send you our HIPAA security overview so she has the technical details."],
    ["amara", "Great. She'll be happy with both."],
    ["marcus", "What about support during setup? Did you get answers quickly?"],
    ["amara", "Very quickly. The chat support was excellent. The knowledge base was thin though. I ended up asking the same three questions."],
    ["sofia", "Can you list them? We can turn them into articles this week.", "kb"],
    ["amara", "Sure. Importing users from a CSV, setting business hours per clinic, and merging duplicate patient contacts."],
    ["marcus", "Perfect, that's a very concrete list. Sofia will write those three articles."],
    ["amara", "One more thing. Training. I'd like a short checklist I can hand to each new employee."],
    ["marcus", "We can create a one-page quick start for clinics. I'll draft it and send it to you for feedback.", "act-quickstart"],
    ["amara", "Thank you, that will be used constantly."],
    ["marcus", "Last question. On a scale of zero to ten, how likely are you to recommend us?"],
    ["amara", "An eight. It would be a nine if onboarding were smoother.", "nps"],
    ["marcus", "That's fair and useful. Thanks Amara, I'll send a summary this afternoon."],
  ],
  analysis: {
    summary:
      "Ninety-day onboarding retrospective with Helix Health, now live in four clinics. Feedback is positive on the queue view and support responsiveness, but the first two weeks suffered from invitation emails landing in spam and a blank first screen. Amara wants a team-lead role so clinic managers can view reports without billing access, a signed HIPAA business associate agreement for her compliance officer, better knowledge base coverage and a one-page clinic quick start. She rated the product an 8 out of 10, and a 9 if onboarding improved.",
    topics: ["Onboarding", "Permissions", "HIPAA", "Knowledge base", "Training"],
    keyPoints: [
      ["Live in four clinics; staff like the queue view.", "overall"],
      ["Invitation emails went to spam and new users landed on a blank screen.", "onboarding-pain"],
      ["Clinic managers cannot see their own reports without admin rights.", "roles"],
      ["Compliance officer is still waiting on a signed business associate agreement.", "baa"],
      ["Likelihood to recommend is 8 out of 10, a 9 if onboarding improved.", "nps"],
    ],
    decisions: [
      ["Marcus drafts a one-page clinic quick start for Amara to review.", "act-quickstart", "marcus"],
      ["Helix Health is next in line for guided setup after the pilot.", "onboarding-pain", "marcus"],
    ],
    actions: [
      ["Chase legal for the signed business associate agreement", "marcus", "act-baa", "Today"],
      ["Write knowledge base articles on CSV user import, per-clinic business hours and merging duplicate contacts", "sofia", "kb", "This week"],
      ["Draft a one-page quick start for clinics", "marcus", "act-quickstart"],
      ["Send the HIPAA security overview to Amara's compliance officer", "sofia", "act-baa"],
    ],
    highlights: [
      ["Onboarding was the weak point", "Spam-filtered invites and a blank first screen made the first two weeks hard.", "onboarding-pain"],
      ["NPS-style rating: 8", "Would be a 9 with smoother onboarding.", "nps"],
    ],
    questions: [
      ["How likely are you to recommend us, zero to ten?", "marcus", "nps", true],
    ],
    risks: [
      ["Unsigned BAA could block the compliance officer's sign-off.", "medium", "baa"],
    ],
    sections: {
      topics: [
        ["Onboarding: invites in spam, blank first screen.", "onboarding-pain"],
        ["Permissions: managers need reports without billing access.", "roles"],
        ["Compliance: HIPAA business associate agreement outstanding.", "baa"],
        ["Knowledge base gaps: CSV import, business hours, merging contacts.", "kb"],
      ],
    },
  },
};

export const leadership: MeetingDraft = {
  id: "weekly-leadership-sync",
  title: "Weekly Leadership Sync",
  daysAgo: 9,
  time: [8, 30],
  durationMin: 29,
  template: "general",
  tags: ["Leadership", "Weekly"],
  participants: [lumen.priya, lumen.aditya, lumen.marcus, lumen.dana],
  script: [
    ["priya", "Let's keep this to thirty minutes. Agenda: pipeline, Acme, hiring, and anything blocking."],
    ["dana", "Pipeline is healthy. Eleven qualified opportunities, four in late stage. Two of those are waiting on SSO, so the October date is now a revenue question.", "pipeline"],
    ["priya", "Which ones?"],
    ["dana", "Northstar Bank and a logistics company. Both want the SSO date in writing.", "sso-writing"],
    ["aditya", "I can commit to October twenty first internally. I'm reluctant to put it in a contract before certificate rotation is done."],
    ["priya", "Then we say target October, and we tell them the pilot sandbox is available earlier.", "sso-messaging"],
    ["marcus", "Acme review is tomorrow. Helen is the sponsor and she cares about the four-region timeline. Grace will press on audit logs and data residency."],
    ["priya", "I'll lead with the pilot plan and the SSO date, then go to the residency options. Sofia should be ready with the architecture."],
    ["marcus", "She is working on it. I'd also like us to offer a stopgap for deprovisioning. That's their audit worry."],
    ["aditya", "A bulk deprovision endpoint is small. I can propose it in the meeting if they raise it.", "deprov-idea"],
    ["priya", "Good, propose it if it comes up. Now hiring. Where are we?"],
    ["aditya", "Two senior frontend candidates in final rounds, one backend offer out. I'd like a decision on the frontend role by the end of next week.", "hiring"],
    ["priya", "What's the budget position?"],
    ["dana", "Current bookings support both roles if the two stalled deals close. If they don't, we can only afford one."],
    ["priya", "Then let's hire one frontend engineer now and make the second contingent on those deals. Aditya, is that OK?", "hiring-decision"],
    ["aditya", "Yes, that works. I'd rather hire one great person than two okay ones."],
    ["marcus", "Customer health. Two accounts are at risk, both because of onboarding. A logistics customer and a regional bank."],
    ["priya", "Marcus, please write up the retention plan for both, with specific asks from engineering.", "act-retention"],
    ["marcus", "Will do by Thursday."],
    ["dana", "One more thing. Marketing asked if we can publish the Acme case study. It's early but the story is good."],
    ["priya", "Not until they've been live in all regions. Let's revisit in Q1.", "case-study"],
    ["aditya", "Blockers from me: none, except that I'm the single point of failure on SSO. I'd like to pull Nina fully onto it next week."],
    ["priya", "Approved. Pull Nina onto SSO and pause her other work.", "nina"],
    ["aditya", "Thanks, I'll tell her today."],
    ["priya", "Good. Same time next week. Thanks all."],
  ],
  analysis: {
    summary:
      "Weekly leadership sync covering pipeline, the Acme review, hiring and account health. Two late-stage deals depend on SSO, so the October date is now a revenue issue; the team will say target October and offer an earlier sandbox instead of a contractual date. The team will hire one frontend engineer now, with a second contingent on stalled deals closing. Two accounts are at risk from onboarding problems, and Nina will move fully onto SSO.",
    topics: ["Pipeline", "Acme review", "Hiring", "Account health", "SSO"],
    keyPoints: [
      ["Eleven qualified opportunities, four late stage, two waiting on SSO.", "pipeline"],
      ["Both waiting deals want the SSO date in writing.", "sso-writing"],
      ["Two accounts are at risk because of onboarding.", "act-retention"],
    ],
    decisions: [
      ["Say target October and offer an earlier sandbox instead of contractually committing the SSO date.", "sso-messaging", "priya"],
      ["Hire one frontend engineer now; the second is contingent on the stalled deals closing.", "hiring-decision", "priya"],
      ["Hold the Acme case study until they are live in all regions.", "case-study", "priya"],
      ["Pull Nina fully onto SSO next week.", "nina", "priya"],
    ],
    actions: [
      ["Write the retention plan for the two at-risk accounts with specific engineering asks", "marcus", "act-retention", "Thursday"],
      ["Propose the bulk deprovision endpoint at the Acme review if raised", "aditya", "deprov-idea", "Tomorrow"],
      ["Decide on the senior frontend role", "aditya", "hiring", "End of next week"],
      ["Tell Nina she is moving onto SSO", "aditya", "nina", "Today"],
    ],
    highlights: [
      ["SSO is a revenue issue", "Two late-stage deals wait on the October date.", "pipeline"],
      ["One great hire beats two okay ones", "One frontend hire now; a second only if deals close.", "hiring-decision"],
    ],
    questions: [
      ["Can we publish the Acme case study now?", "dana", "case-study", true],
    ],
    risks: [
      ["Aditya is the single point of failure on SSO.", "medium", "nina"],
      ["If the stalled deals do not close, only one hire is affordable.", "medium", "hiring-decision"],
    ],
    sections: {
      topics: [
        ["Pipeline health and SSO dependency.", "pipeline"],
        ["Preparation for the Acme review.", "deprov-idea"],
        ["Hiring plan for the frontend role.", "hiring-decision"],
        ["Account health and the retention plan.", "act-retention"],
      ],
    },
  },
};
