import type { MeetingDraft } from "./build";

const lumen = {
  priya: { id: "priya", name: "Priya Raman", role: "VP Product", org: "Lumen" },
  aditya: { id: "aditya", name: "Aditya Sharma", role: "Engineering Lead", org: "Lumen" },
  marcus: { id: "marcus", name: "Marcus Bell", role: "Customer Success Manager", org: "Lumen" },
  sofia: { id: "sofia", name: "Sofia Alvarez", role: "Solutions Architect", org: "Lumen" },
  dana: { id: "dana", name: "Dana Whitfield", role: "Account Executive", org: "Lumen" },
};

export const engSync: MeetingDraft = {
  id: "weekly-engineering-sync",
  title: "Weekly Engineering Sync",
  daysAgo: 2,
  time: [9, 30],
  durationMin: 32,
  template: "engineering",
  tags: ["Engineering", "Weekly"],
  participants: [
    lumen.aditya,
    { id: "nina", name: "Nina Petrov", role: "Backend Engineer", org: "Lumen" },
    { id: "leo", name: "Leo Tan", role: "Frontend Engineer", org: "Lumen" },
    { id: "sara", name: "Sara Mehta", role: "Site Reliability Engineer", org: "Lumen" },
  ],
  script: [
    ["aditya", "Morning everyone. Quick agenda: SAML status, last week's webhook incident, the Sydney latency report, and the migration off the old job queue."],
    ["nina", "SAML first. The Okta flow passes end to end in staging. Azure AD is working for sign in but the attribute mapping for groups is still failing.", "saml-status"],
    ["aditya", "Is the group mapping blocking the October twenty first date?"],
    ["nina", "Not blocking, we only need group sync for SCIM. But the metadata refresh on certificate rotation is a real gap. If an IdP rotates its cert, login breaks until we re-import.", "cert-rotation"],
    ["aditya", "That one worries me. Can we poll the metadata URL instead of storing a static cert?"],
    ["nina", "Yes. I'd poll every six hours and alert on failure. It's about two days of work.", "poll-metadata"],
    ["aditya", "Do it. Please treat it as part of the SSO scope and not as a follow-up."],
    ["leo", "On the frontend side, the SSO settings page is done except the error states. I need copy for the failure messages, like an expired assertion or a domain mismatch."],
    ["aditya", "I'll ask Priya for copy today. Don't block on it, ship with placeholder text behind the flag.", "copy-action"],
    ["sara", "Now the incident. Last Thursday webhooks were delayed by up to forty minutes for about ninety customers.", "incident"],
    ["sara", "Root cause was retry storms. A customer endpoint returned five hundreds, our workers retried with a fixed two second delay, and the queue backed up behind them."],
    ["nina", "We had no jitter and no per-endpoint circuit breaker. It's my code, so I'll own the fix."],
    ["aditya", "What's the fix?"],
    ["nina", "Exponential backoff with jitter, cap at fifteen minutes, and a circuit breaker per endpoint that opens after fifty consecutive failures. Failed events go to a dead letter queue the customer can replay from the dashboard.", "backoff-design"],
    ["sara", "I'd add a per-tenant concurrency limit too, so one bad endpoint can't starve others. Otherwise we still have a noisy neighbour problem."],
    ["aditya", "Agreed, include the tenant concurrency limit. Sara, can you add an alert on queue age over five minutes? We only found this from a customer email.", "queue-alert"],
    ["sara", "Yes, I'll set that up today. Page on ten minutes, warn on five."],
    ["aditya", "Good. Nina, target for the webhook fix?"],
    ["nina", "Backoff and breaker by Wednesday. Dead letter replay UI needs Leo, so probably the week after.", "webhook-date"],
    ["leo", "Fine, I can pick that up after the SSO page."],
    ["aditya", "Sydney latency next. A customer reports slow first load. Sara, do we see anything?"],
    ["sara", "Sydney traffic is served from Singapore. Median first byte is around four hundred milliseconds, and the p95 is over two seconds, mostly TLS handshakes plus uncached bundles.", "sydney"],
    ["leo", "The main bundle is also too large. It's over one point six megabytes gzipped because the charting library isn't code split."],
    ["aditya", "Then two fixes: turn on the Sydney edge, and split the charting bundle. Leo, take the bundle, Sara the edge.", "sydney-plan"],
    ["sara", "The edge needs a DNS change and a certificate, roughly a day, but I want to do it off peak."],
    ["aditya", "Last topic, the old job queue migration. Where are we?"],
    ["nina", "Eleven of the thirty job types have moved. The remaining ones are the scheduled reports and the export jobs, and those are the riskiest.", "queue-migration"],
    ["aditya", "Let's not move exports until the webhook work is done. We can't afford two queue changes in one release.", "freeze"],
    ["nina", "Agreed. I'll pause the migration after the reports jobs."],
    ["aditya", "Great, thanks all. Notes go in the channel."],
  ],
  analysis: {
    summary:
      "SAML SSO passes end to end on Okta in staging; Azure AD group mapping is failing but does not block the October 21 date. Certificate rotation is a real gap and will be handled by polling IdP metadata every six hours. The team reviewed last Thursday's webhook delay incident (retry storm from a failing customer endpoint) and agreed on backoff with jitter, per-endpoint circuit breakers, a dead-letter queue and a tenant concurrency limit. Sydney latency will be tackled with a new edge and bundle splitting, and the job queue migration pauses after the reports jobs.",
    topics: ["SAML SSO", "Webhook incident", "Sydney latency", "Job queue migration"],
    keyPoints: [
      ["Okta SAML works end to end in staging; Azure AD group attribute mapping still fails.", "saml-status"],
      ["Webhook delays of up to 40 minutes hit about 90 customers due to retry storms.", "incident"],
      ["Sydney p95 first byte is over two seconds; the main bundle exceeds 1.6 MB gzipped.", "sydney"],
      ["Eleven of thirty job types have moved to the new queue.", "queue-migration"],
    ],
    decisions: [
      ["Poll IdP metadata every six hours instead of storing a static certificate, as part of SSO scope.", "poll-metadata", "aditya"],
      ["Webhook fix uses exponential backoff with jitter, per-endpoint circuit breakers, a dead-letter queue and per-tenant concurrency limits.", "backoff-design", "aditya"],
      ["Split the Sydney fix into a new edge (Sara) and charting bundle splitting (Leo).", "sydney-plan", "aditya"],
      ["Freeze the export jobs migration until the webhook work ships.", "freeze", "aditya"],
    ],
    actions: [
      ["Ship exponential backoff and circuit breaker for webhooks", "nina", "webhook-date", "Wednesday"],
      ["Add a queue-age alert (warn at 5 min, page at 10 min)", "sara", "queue-alert", "Today"],
      ["Get SSO failure-message copy from Priya for Leo", "aditya", "copy-action", "Today"],
      ["Poll IdP metadata for certificate rotation", "nina", "poll-metadata"],
      ["Turn on the Sydney edge and split the charting bundle", "sara", "sydney-plan"],
    ],
    highlights: [
      ["Root cause of webhook delays", "Fixed two-second retries with no jitter or circuit breaker caused queue backup.", "incident"],
      ["Certificate rotation gap", "If an IdP rotates its cert, login breaks until re-import.", "cert-rotation"],
    ],
    questions: [
      ["Is the Azure AD group mapping failure blocking the October 21 date?", "aditya", "saml-status", true],
    ],
    risks: [
      ["Static IdP certificates would break SSO login on rotation.", "high", "cert-rotation"],
      ["Two queue changes in one release could destabilise exports.", "medium", "freeze"],
    ],
    sections: {
      technical: [
        ["Poll IdP metadata every six hours and alert on failure.", "poll-metadata"],
        ["Exponential backoff capped at 15 minutes, breaker opens after 50 consecutive failures.", "backoff-design"],
      ],
      blockers: [
        ["Azure AD group attribute mapping still failing (not blocking SSO date).", "saml-status"],
        ["Dead-letter replay UI depends on Leo finishing the SSO settings page.", "webhook-date"],
      ],
      incidents: [
        ["Webhook delays of up to 40 minutes for ~90 customers, discovered via a customer email rather than an alert.", "incident"],
        ["Charting library is not code split, inflating the main bundle.", "sydney"],
      ],
    },
  },
};

export const brightwave: MeetingDraft = {
  id: "discovery-brightwave-logistics",
  title: "Discovery Call: Brightwave Logistics",
  daysAgo: 3,
  time: [14, 0],
  durationMin: 38,
  template: "discovery",
  tags: ["Discovery", "Customer"],
  participants: [
    lumen.priya,
    { id: "carla", name: "Carla Mendes", role: "Operations Manager", org: "Brightwave Logistics" },
    { id: "raj", name: "Raj Patel", role: "Support Team Lead", org: "Brightwave Logistics" },
  ],
  script: [
    ["priya", "Thanks for joining, Carla and Raj. I'm not here to pitch today. I want to understand how your support team works and where it hurts."],
    ["carla", "Sounds good. We're a freight forwarder with about sixty people in operations. Support is twelve people handling shipment questions from shippers and truckers."],
    ["priya", "Walk me through what happens when a customer emails about a delayed shipment."],
    ["raj", "It lands in a shared mailbox. Someone claims it by replying all, which is chaos, then they look up the shipment in our tracking system and copy the status back into the email.", "workaround-mailbox"],
    ["priya", "How often does that go wrong?"],
    ["raj", "Twice a week two people answer the same email. Customers get contradicting answers and they are furious.", "pain-duplicates"],
    ["carla", "It's the thing that keeps me up. We lost a mid-size account last quarter because they got two different ETAs on the same container."],
    ["priya", "That's painful. What have you tried?"],
    ["raj", "We tried a spreadsheet to claim tickets. It worked for a month and then people stopped updating it. We also tried a free help desk tool, but nobody wanted to log into yet another system.", "workaround-sheet"],
    ["carla", "Onboarding was the killer. We spent two weeks setting up the free tool and then adoption dropped after three days because agents didn't understand what to do first.", "pain-onboarding"],
    ["priya", "So the setup burden and first-week experience mattered as much as features."],
    ["carla", "More. I would pay for a tool that my newest hire can use on day one without a training session.", "quote-day-one"],
    ["raj", "And it must connect to our tracking system. Otherwise we're still copy and pasting. We have an API but nobody has time to build against it.", "pain-integration"],
    ["priya", "What does your IT side look like? Would anything like single sign-on matter?"],
    ["carla", "Our IT guy will insist on SSO. We use Microsoft accounts for everything. If a tool can't do that, he won't approve it.", "sso"],
    ["raj", "He also asks about offboarding. Truckers' dispatchers come and go, and he had an incident where an ex-contractor still had access to a system for a month."],
    ["priya", "Understood. How do you measure whether support is doing well today?"],
    ["carla", "Honestly we don't. I count complaints. Raj, you check first response time in the mailbox, but that's manual."],
    ["raj", "I export the mailbox to a spreadsheet on Fridays. It takes me about ninety minutes.", "pain-reporting"],
    ["carla", "If I could open a dashboard on Monday and see response time and the biggest categories, that would be enormous for us."],
    ["priya", "What would make you say no to a new tool?"],
    ["carla", "Price per seat if it's too high. We're twelve agents, and freight margins are thin. And a long implementation. I can't lose a month."],
    ["raj", "Also mobile. Some of our staff are on the warehouse floor with tablets."],
    ["priya", "That's very helpful. If I sent a short summary of what I heard, would you be open to a follow-up in two weeks?"],
    ["carla", "Yes. And if you can show me the onboarding experience in that follow-up, even better."],
    ["priya", "Great, I'll set that up. Thanks both, this was really honest.", "followup"],
  ],
  analysis: {
    summary:
      "Discovery conversation with Brightwave Logistics, a freight forwarder whose 12-person support team works from a shared mailbox. Their core pains are duplicate replies that have already cost them an account, painful onboarding that killed adoption of a previous free tool, no integration with their tracking system, and manual Friday reporting. SSO through Microsoft accounts and clean offboarding are prerequisites from their IT lead. They want a tool a new hire can use on day one, and a follow-up in two weeks that shows the onboarding experience.",
    topics: ["Shared mailbox chaos", "Onboarding", "Tracking integration", "SSO", "Reporting"],
    keyPoints: [
      ["Two agents answer the same email about twice a week, giving contradicting ETAs; one account has already been lost.", "pain-duplicates"],
      ["A previous free help desk tool failed because agents did not know what to do first.", "pain-onboarding"],
      ["No integration with the tracking system means copy and pasting statuses.", "pain-integration"],
      ["IT will insist on Microsoft SSO and reliable offboarding.", "sso"],
      ["Support reporting is a 90-minute manual export each Friday.", "pain-reporting"],
    ],
    decisions: [
      ["Schedule a follow-up in two weeks focused on the onboarding experience.", "followup", "priya"],
    ],
    actions: [
      ["Send Carla and Raj a summary of what was heard and schedule the follow-up", "priya", "followup", "This week"],
    ],
    highlights: [
      ["A lost account from duplicate ETAs", "Two different ETAs on the same container cost Brightwave a mid-size account.", "pain-duplicates"],
      ["Day-one usability is the requirement", "Would pay for a tool a new hire can use on day one without training.", "quote-day-one"],
      ["SSO is a gate for IT approval", "Microsoft SSO is non-negotiable.", "sso"],
    ],
    questions: [
      ["Would single sign-on matter?", "priya", "sso", true],
    ],
    risks: [
      ["Per-seat price sensitivity in thin-margin freight.", "medium", "followup"],
    ],
    sections: {
      pains: [
        ["Two agents reply to the same email, sending contradicting answers.", "pain-duplicates"],
        ["Adoption collapsed three days after setup because agents were unsure what to do first.", "pain-onboarding"],
        ["Copy and paste between tracking system and email because there is no integration.", "pain-integration"],
        ["Friday reporting takes ninety minutes by hand.", "pain-reporting"],
      ],
      workarounds: [
        ["Shared mailbox where people claim emails by replying all.", "workaround-mailbox"],
        ["A spreadsheet to claim tickets, abandoned after a month; a free help desk tool abandoned after three days.", "workaround-sheet"],
      ],
      quotes: [
        ["I would pay for a tool that my newest hire can use on day one without a training session.", "quote-day-one"],
        ["Twice a week two people answer the same email.", "pain-duplicates"],
      ],
    },
  },
};

export const northstar: MeetingDraft = {
  id: "sales-northstar-bank-demo",
  title: "Northstar Bank: Demo & Pricing",
  daysAgo: 4,
  time: [16, 0],
  durationMin: 41,
  template: "sales",
  tags: ["Sales", "Enterprise"],
  participants: [
    lumen.dana,
    lumen.sofia,
    { id: "elena", name: "Elena Rossi", role: "Head of Customer Operations", org: "Northstar Bank" },
    { id: "mark", name: "Mark Hale", role: "Procurement Manager", org: "Northstar Bank" },
  ],
  script: [
    ["dana", "Thanks for the time, Elena and Mark. I'll do a short demo focused on what you told me last week, then we can talk about pricing and process."],
    ["elena", "Great. Just so you know, I have budget approved for this fiscal year, but it expires in December, so timing matters."],
    ["dana", "That's really helpful context. So a decision by early November would work?", "timeline"],
    ["elena", "Ideally, yes. We want the pilot running before the year-end freeze.", "signal-budget"],
    ["sofia", "Let me show the agent workspace. This is a live queue with SLA timers, and here you can see the customer's history on one screen."],
    ["elena", "The SLA timers are exactly what my compliance team asks for. Can breach alerts go to a supervisor's phone?"],
    ["sofia", "Yes, via email or push, and we're adding SMS next quarter."],
    ["elena", "SMS isn't a blocker. Now, our biggest concern is security. We're a bank, and we can't run anything that isn't SOC 2 and have single sign-on with our identity provider.", "objection-security"],
    ["dana", "We're SOC 2 Type II, and SAML single sign-on is going generally available in October. I can send our security package this week."],
    ["elena", "The October date is tight for us. What if it slips?", "objection-sso-date"],
    ["dana", "Fair question. I'd propose a pilot on a sandbox with a small team, so you're not depending on the date for production."],
    ["mark", "From procurement's side, we have a vendor risk assessment that usually takes six weeks. I'd need the security package in the first week."],
    ["dana", "We'll send it Monday. Do you know which questionnaire format you use?"],
    ["mark", "We use the standard shared assessment format. I'll send you the exact template."],
    ["elena", "On competitors, we're currently looking at two other vendors. HelpForge has a strong reporting story, and Ticketly is cheaper.", "competitors"],
    ["dana", "What do you like most about HelpForge's reporting?"],
    ["elena", "It has scheduled executive reports. My director wants one email each Monday with response time and backlog."],
    ["sofia", "We have scheduled reports for team leads today and the executive summary format is on the roadmap. I can show a preview."],
    ["elena", "A preview would help. Reporting is the second requirement after security.", "signal-reporting"],
    ["dana", "Let's talk pricing. For a hundred and forty agents on the enterprise plan, we're at sixty two dollars per seat per month on an annual contract."],
    ["mark", "That's higher than Ticketly, who quoted us forty eight. Is there flexibility?", "objection-price"],
    ["dana", "There is on term length. On a three-year commitment I can bring the number down to fifty six, and SSO and audit logs are included at no extra cost."],
    ["mark", "Three years is long for us. We'd prefer two."],
    ["dana", "Let me check what two years can look like and come back with both options in writing."],
    ["elena", "One more. Who from your team would help us on implementation?"],
    ["sofia", "I'd be your solutions architect, and you'd also get a named customer success manager. Typical go-live for a team your size is six weeks."],
    ["elena", "That's acceptable. Let's do this: you send the security package Monday and the pricing options Wednesday, and we'll schedule a pilot scoping call after that.", "nextsteps"],
    ["dana", "Perfect. I'll send a calendar invite for the scoping call today."],
    ["mark", "Sounds good."],
  ],
  analysis: {
    summary:
      "Demo and pricing conversation with Northstar Bank. Elena has an approved budget that expires in December and wants a pilot running before the year-end freeze. Requirements are SOC 2, SAML SSO and SLA timers, followed by scheduled executive reporting. Objections centre on the October SSO date and price versus Ticketly ($48 per seat against $62 quoted). Dana will send the security package Monday and two pricing options (two and three-year terms) Wednesday, then a pilot scoping call follows.",
    topics: ["Budget & timeline", "Security & SSO", "Competitors", "Pricing", "Implementation"],
    keyPoints: [
      ["Budget is approved for this fiscal year but expires in December.", "signal-budget"],
      ["Security (SOC 2, SSO) is the gating requirement; reporting is second.", "objection-security"],
      ["Competing vendors are HelpForge (reporting) and Ticketly (price, quoted $48/seat).", "competitors"],
      ["Proposed price is $62 per seat per month; three-year term brings it to $56.", "objection-price"],
      ["Typical go-live for a team of this size is six weeks.", "nextsteps"],
    ],
    decisions: [
      ["Send the security package Monday and pricing options Wednesday, then hold a pilot scoping call.", "nextsteps", "dana"],
    ],
    actions: [
      ["Send SOC 2 security package to procurement", "dana", "nextsteps", "Monday"],
      ["Send written pricing options for two and three-year terms", "dana", "objection-price", "Wednesday"],
      ["Send the vendor risk questionnaire template", "mark", "nextsteps", "This week"],
      ["Prepare a preview of executive summary reporting", "sofia", "signal-reporting"],
    ],
    highlights: [
      ["Budget expires in December", "Elena wants a pilot running before the year-end freeze.", "signal-budget"],
      ["Price objection vs. Ticketly", "Ticketly quoted $48 per seat against Lumen's $62.", "objection-price"],
      ["SSO date risk", "The October GA date is tight for the bank.", "objection-sso-date"],
    ],
    questions: [
      ["Can SLA breach alerts go to a supervisor's phone?", "elena", "objection-security", true],
      ["What if the SSO date slips?", "elena", "objection-sso-date", true],
    ],
    risks: [
      ["SSO date slipping past October could lose the deal.", "high", "objection-sso-date"],
      ["Six-week vendor risk assessment could collide with the December budget deadline.", "medium", "timeline"],
      ["Ticketly undercuts on price by roughly 23%.", "medium", "objection-price"],
    ],
    sections: {
      signals: [
        ["Approved budget with a December deadline and desire to pilot before year-end freeze.", "signal-budget"],
        ["Reporting named as the second requirement after security.", "signal-reporting"],
      ],
      objections: [
        ["Must be SOC 2 with SSO; October SSO date is tight.", "objection-sso-date"],
        ["Ticketly quoted $48 per seat; three-year term is too long, preferring two.", "objection-price"],
      ],
      competitors: [
        ["HelpForge (strong scheduled reporting) and Ticketly (cheaper).", "competitors"],
      ],
      nextsteps: [
        ["Security package Monday, pricing options Wednesday, then pilot scoping call.", "nextsteps"],
      ],
    },
  },
};
